ChangmokCandy/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/',include('boards.urls')),
    path('accounts/',include('accounts.urls')),
]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'
urlpatterns = [
    path('',views.index,name='index'),
    path('search/',views.search,name='search'),
    path('graph/',views.graph,name='graph'),
    path('totalgraph/',views.totalgraph,name='totalgraph'),
    path('gisangupdate/',views.gisangupdate,name='gisangupdate'),
    path('gisangdelete/',views.gisnagdelete,name='gisangdelete'),
    path('datasend/',views.datasend,name='datasend'),
]

boards/models.py
from django.db import models

# Create your models here.

class Board(models.Model):
    location = models.CharField(max_length=10)
    real_tem = models.IntegerField()
    real_hum = models.IntegerField()
    api_tem = models.IntegerField()
    api_hum = models.IntegerField()
    error_tem = models.IntegerField()
    error_hum = models.IntegerField()
    created_at= models.DateTimeField(auto_now_add=True)
    writer = models.CharField(max_length=30)

class GisangGrid(models.Model):
    si = models.CharField(max_length=20)
    gu = models.CharField(max_length=20,default='default')
    do = models.CharField(max_length=20,default='default')
    gridx = models.IntegerField()
    gridy = models.IntegerField()

boards/views.py
from django.shortcuts import render,redirect,get_object_or_404
from numpy import sign
from api.temhum import send,error,gisangapi
from .models import Board, GisangGrid
from django.views.decorators.http import require_http_methods,require_POST,require_safe
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import pandas as pd
from numpy import NaN
from arduino.arduino_data import data

@require_safe
def index(request):
    boards = Board.objects.order_by('-pk')
    boards = boards.filter(writer=request.user)
    context = {
        'boards':boards,
        'data': data,
    }
    return render(request,'boards/index.html',context)

@login_required
@require_http_methods(['GET','POST'])
def search(request):
    if request.method=='POST':
        longitude = request.POST.get('longitude') # 경도
        latitude = request.POST.get('latitude') # 위도
        temperature = request.POST.get('temperature') #온도
        humidity= request.POST.get('humidity') #습도
        rth = send(longitude,latitude)
        err = error(temperature,humidity)
        gisanggrid = GisangGrid.objects.filter(si=rth[0],gu=rth[1])
        for i in range(gisanggrid.count()):
            if gisanggrid[i].do == 'default':
                gridx = gisanggrid[i].gridx
                gridy = gisanggrid[i].gridy
            if gisanggrid[i].do == rth[2]:
                gridx = gisanggrid[i].gridx
                gridy = gisanggrid[i].gridy
        apirth = gisangapi(rth[2],gridx,gridy)
        board = Board(location=apirth[0],api_tem=apirth[1],api_hum=apirth[2],real_tem=temperature,real_hum=humidity)
        board.error_tem = (apirth[1]-err[0])/apirth[1]*100
        board.error_hum = (apirth[2]-err[1])/apirth[2]*100
        board.writer = request.user
        board.save()
        return redirect('boards:index')
    else:
        if request.GET.get('longitude'):
            longitude = request.GET.get('longitude') # 경도
            latitude = request.GET.get('latitude') # 위도
            temperature = request.GET.get('temperature') #온도
            humidity= request.GET.get('humidity') #습도
            rth = send(longitude,latitude)
            err = error(temperature,humidity)
            gisanggrid = GisangGrid.objects.filter(si=rth[0],gu=rth[1])
            for i in range(gisanggrid.count()):
                if gisanggrid[i].do == 'default':
                    gridx = gisanggrid[i].gridx
                    gridy = gisanggrid[i].gridy
                if gisanggrid[i].do == rth[2]:
                    gridx = gisanggrid[i].gridx
                    gridy = gisanggrid[i].gridy
            apirth = gisangapi(rth[2],gridx,gridy)
            board = Board(location=apirth[0],api_tem=apirth[1],api_hum=apirth[2],real_tem=temperature,real_hum=humidity)
            board.error_tem = (apirth[1]-err[0])/apirth[1]*100
            board.error_hum = (apirth[2]-err[1])/apirth[2]*100
            board.writer = request.user
            board.save()
            return redirect('boards:index')
        else:
            board= Board()
    context = {
        'board':board,
    }
    return render(request,'boards/search.html',context)
    
    

@login_required
@require_safe
def graph(request):
    boards = Board.objects.order_by('-pk')
    boards = boards.filter(writer=request.user)
    key = boards.latest('id')
    board = get_object_or_404(Board,pk=key.pk)
    context = {
        'board':board,
    }
    return render(request,'boards/graph.html',context)

@login_required
@require_safe
def totalgraph(request):
    boards = Board.objects.order_by('-pk')
    boards = boards.filter(writer=request.user)
    apitem = []
    reatem = []
    apihum = []
    reahum = []
    credate =[]
    for i in range(boards.count()):
        apitem.append(boards[i].api_tem)
        reatem.append(boards[i].real_tem)
        apihum.append(boards[i].api_hum)
        reahum.append(boards[i].real_hum)
        credate.append(boards[i].id)
    context = {
        'boards':boards,
        'apitem':apitem,
        'reatem':reatem,
        'apihum':apihum,
        'reahum':reahum,
        'credate':credate,
    }
    return render(request,'boards/totalgraph.html',context)

def gisangupdate(request):
    #엑셀 읽기
    if str(request.user) =='admin':
        a1 = pd.read_excel('gisangapi.xlsx', header=1,engine ='openpyxl')
        #읽은 엑셀을 리스트로변환
        alist = a1.values.tolist()
        for i in range(len(alist)):
            if alist[i][4] is NaN:
                alist[i][4] = 'default'
            if alist[i][5] is NaN:
                alist[i][5] = 'default'
            gisanggrid = GisangGrid(si=alist[i][2],gu=alist[i][3],do=alist[i][4],gridx=alist[i][5],gridy=alist[i][6])
            gisanggrid.save()
        return redirect('boards:search')
    else:
        return redirect('boards:search')

def gisnagdelete(request):
    if str(request.user) =='admin':
        gisanggrid = GisangGrid.objects.all()
        gisanggrid.delete()
        return redirect('boards:search')
    else:
        return redirect('boards:search')

def datasend(request):
    context = {
        'data': data,
    }
    return render(request, 'boards/search.html', context)

boards/templates/boards/graph.html
{% extends 'base.html' %}

{% block content %}
    <div class="row"> 
      <div class="col col-md-6" >
        <canvas id="mytem"></canvas> 
      </div>
      <div class="col col-md-6" >
        <canvas id="myhum"></canvas>  
      </div>
    <div casll="row">
      <p>분석결과</p>
      <p>{{board.location}}의 {{board.created_at|date:"Y-m-d A h:i"}}</p>
      <p>기상청 온도는 {{board.api_tem}}°C, 계측 온도는 {{board.real_tem}}°C 오차율은 {{board.error_tem}}%</p>
      <p>기상청 습도는 {{board.api_hum}}%, 계측 습도는 {{board.real_hum}}% 오차율은 {{board.error_hum}}%</p>
    </div>
      
    </div> 
    <script> 
          var mytem = document.getElementById('mytem'); 
          var mytem = new Chart(mytem, { 
            type: 'bar', 
            data: { 
              labels: ['API 온도', '계측 온도'], 
              datasets: [{ 
                label: '{{board.location}} 의 온도', 
                data: [{{board.api_tem}},{{board.real_tem}}], 
                backgroundColor: [ 
                  'rgba(255, 99, 132, 0.2)', 
                  'rgba(54, 162, 235, 0.2)',  
                ], 
                borderColor: [ 
                  'rgba(255, 99, 132, 1)', 
                  'rgba(54, 162, 235, 1)', 
                ], 
                borderWidth: 2 
              }] 
            }, 
            options: {
                legend: {
                    display: false
                },
                tooltips: {
                    callbacks: {
                      label: function(tooltipItem) {
                              return tooltipItem.yLabel;
                      }
                    }
                },
              scales: { 
                yAxes: [{ 
                  ticks: {
                    min:0,
                    max:40, 
                    beginAtZero: true 
                  } 
                }] 
              }
            }
          }); 
      </script> 
      <script> 
        var myhum = document.getElementById('myhum'); 
        var myhum = new Chart(myhum, { 
          type: 'bar', 
          data: { 
            labels: ['API 습도', '계측 습도'], 
            datasets: [{ 
              label: '{{board.location}} 의 습도', 
              data: [{{board.api_hum}},{{board.real_hum}}], 
              backgroundColor: [ 
                'rgba(255, 99, 132, 0.2)', 
                'rgba(54, 162, 235, 0.2)',  
              ], 
              borderColor: [ 
                'rgba(255, 99, 132, 1)', 
                'rgba(54, 162, 235, 1)', 
              ], 
              borderWidth: 2 
            }] 
          }, 
          options: {
                legend: {
                    display: false
                },
                tooltips: {
                    callbacks: {
                      label: function(tooltipItem) {
                              return tooltipItem.yLabel;
                      }
                    }
                },
              scales: { 
                yAxes: [{ 
                  ticks: { 
                    min:0,
                    max:100,
                    beginAtZero: true 
                  } 
                }] 
              }
            }
          }); 
      </script> 
{% endblock content %}

boards/templates/boards/index.html
{% extends 'base.html' %}

{% block content %}
  {% for board in boards %}
    <div>{{board.pk}}</div>
    <div>{{board.real_tem}} {{board.api_tem}}</div>
    <div>{{board.real_hum}} {{board.api_hum}}</div>
    <div>{{board.location}}</div>
    <hr>
  {% endfor %}

{% endblock content %}

boards/templates/boards/search.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<a class="btn btn-light" href="{% url 'boards:gisangupdate' %}">API 업데이트</a>
<form action="{% url 'boards:gisangdelete' %}" method='POST'>
  {% csrf_token %}
  {% bootstrap_button "API 삭제하기" button_type="submit" button_class="btn-success" %}
  </div>
</form>
<form action="{% url 'boards:search' %}" method='POST'>
  {% csrf_token %}
  <div class="p-1">
    <label for="longitude">경도: </label>
    <input type="text" id="longitude" name="longitude">
  </div>
    <div class="p-1">
    <label for="latitude">위도: </label>
    <input type="text" id="latitude" name="latitude">
  </div>
    <div class="p-1">
    <label for="temperature">온도: </label>
    <input type="number" id="temperature" name="temperature">
  </div>
    <div class="p-1">
    <label for="humidity">습도: </label>
    <input type="number" id="humidity" name="humidity">
  </div>
  <div class="mt-2">
    {% bootstrap_button "작성하기" button_type="submit" button_class="btn-success" %}
    {% bootstrap_button "리셋하기" button_type="reset" button_class="btn-light" %}
    <a class="btn btn-light" href="{% url 'boards:index' %}">뒤로가기</a>
  </div>
</form>
<form action="{% url 'boards:datasend' %}">
    {% bootstrap_button "입력하기" button_type="submit" button_class="btn-light" %}
</form>
{% endblock content %}

boards/templates/boards/totalgraph.html
{% extends 'base.html' %}

{% block content %}
    <div class="row"> 
      <div class="col col-md-6" >
        <canvas id="mytem"></canvas> 
      </div>
      <div class="col col-md-6" >
        <canvas id="myhum"></canvas>  
      </div>

    <script> 
          var mytem = document.getElementById('mytem'); 
          var mytem = new Chart(mytem, { 
            type: 'line', 
            data: { 
              labels:{{credate}},
              datasets: [{  
                label: '기상청 온도',
                type: 'line', 
                fill: false,
                lineTension : 0.2,  // 0이면 꺾은선 그래프, 숫자가 높을수록 둥글해짐
                pointRadius : 0,    // 각 지점에 포인트 주지 않음
                data: {{apitem}}, 
                borderColor: 'rgba(255, 99, 132, 0.2)',
                borderWidth: 5 
              },{
                label: '계측 온도',  
                type: 'line', 
                fill: false,
                lineTension : 0.2,  // 0이면 꺾은선 그래프, 숫자가 높을수록 둥글해짐
                pointRadius : 0,    // 각 지점에 포인트 주지 않음
                data: {{reatem}}, 
                borderColor: 'rgba(54, 162, 235, 0.2)',
                borderWidth: 5 
              }] 
            },
            options: {
              scales: { 
                yAxes: [{ 
                  ticks: {
                    min:0,
                    max:40, 
                    beginAtZero: true 
                  } 
                }] 
              }
            }
          }); 
      </script>
      <script>
        var myhum = document.getElementById('myhum'); 
        var myhum = new Chart(myhum, { 
            type: 'line', 
            data: { 
              labels:{{credate}},
              datasets: [{  
                label: '기상청 습도',
                type: 'line', 
                fill: false,
                lineTension : 0.2,  // 0이면 꺾은선 그래프, 숫자가 높을수록 둥글해짐
                pointRadius : 0,    // 각 지점에 포인트 주지 않음
                data: {{apihum}}, 
                borderColor: 'rgba(255, 99, 132, 0.2)',
                borderWidth: 5 
              },{
                label: '계측 습도',  
                type: 'line', 
                fill: false,
                lineTension : 0.2,  // 0이면 꺾은선 그래프, 숫자가 높을수록 둥글해짐
                pointRadius : 0,    // 각 지점에 포인트 주지 않음
                data:{{reahum}}, 
                borderColor: 'rgba(54, 162, 235, 0.2)',
                borderWidth: 5 
              }] 
            },
            options: {
              scales: { 
                yAxes: [{ 
                  ticks: {
                    min:0,
                    max:100, 
                    beginAtZero: true 
                  } 
                }] 
              }
            }
          }); 
      </script> 
{% endblock content %}