ChangmokCandy/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/',include('boards.urls')),
    path('accounts/',include('accounts.urls')),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('signup/',views.signup,name='signup'),
    path('delete/',views.delete,name='delete'),
    path('update/',views.update,name='update'),
    path('password/',views.change_password,name='change_password')
]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'
urlpatterns = [
    path('',views.index,name='index'),
    path('search/',views.search,name='search'),
    path('graph/',views.graph,name='graph'),
    path('totalgraph/',views.totalgraph,name='totalgraph'),
    path('gisangupdate/',views.gisangupdate,name='gisangupdate'),
    path('gisangdelete/',views.gisnagdelete,name='gisangdelete'),
    path('datasend/',views.datasend,name='datasend'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model

class CustonUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('email','first_name','last_name',)

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm,PasswordChangeForm
from .forms import CustonUserChangeForm
from django.views.decorators.http import require_http_methods,require_POST
from django.contrib.auth.decorators import login_required

@require_http_methods(['GET','POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('boards:index')
    if request.method =='POST':
        form = AuthenticationForm(request,request.POST)
        if form.is_valid():
            auth_login(request,form.get_user())
            return redirect(request.GET.get('next') or 'boards:index')
    else:
        form = AuthenticationForm()
    context = {
        'form':form,
    }
    return render(request,'accounts/login.html',context)

@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('boards:index')

@require_http_methods(['GET','POST'])
def signup(request):
    if request.method =='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request,user)
            return redirect('boards:index')
    else:
        form = UserCreationForm()
    context = {
        'form':form,
    }
    return render(request,'accounts/signup.html',context)

@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
    return redirect('boards:index')

@require_http_methods(['GET','POST'])
def update(request):
    if request.method =='POST':
        form = CustonUserChangeForm(request.POST,instance=request.user)
        if form.is_valid:
            form.save()
            return redirect('boards:index')
    else:
        form = CustonUserChangeForm(instance=request.user)
    context = {
        'form':form,
    }
    return render(request,'accounts/update.html',context)

@login_required
@require_http_methods(['GET','POST'])
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user,request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            return redirect('boards:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form':form,
    }
    return render(request,'accounts/change_password.html',context)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<form action="{% url 'accounts:change_password' %}" method='POST' class="mb-3">
{% csrf_token %}
{% bootstrap_form form%}
{% bootstrap_button "비밀번호변경" button_type="submit" button_class="btn-success" %}
<a class="btn btn-light" href="{% url 'accounts:update' %}">뒤로가기</a>
</form>

{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<form action="" method='POST' class="mb-3">
{% csrf_token %}
{% bootstrap_form form%}
{% bootstrap_button "로그인" button_type="submit" button_class="btn-success" %}
<a class="btn btn-light" href="{% url 'boards:index' %}">뒤로가기</a>
</form>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
  <form action="{% url 'accounts:signup' %}" method='POST' class="mb-3">
  {% csrf_token %}
  {% bootstrap_form form%}
  {% bootstrap_button "회원가입" button_type="submit" button_class="btn-success" %}
  <a class="btn btn-light" href="{% url 'boards:index' %}">뒤로가기</a>
  </form>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<form action="" method='POST' class="mb-3">
{% csrf_token %}
{% bootstrap_form form%}
<div class="mt-3"></div>
{% bootstrap_button "정보수정" button_type="submit" button_class="btn-success" %}
<a class="btn btn-light" href="{% url 'boards:index' %}">뒤로가기</a>
</form>
{% endblock content %}