ChangmokCandy/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/',include('boards.urls')),
    path('accounts/',include('accounts.urls')),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('signup/',views.signup,name='signup'),
    path('delete/',views.delete,name='delete'),
    path('update/',views.update,name='update'),
    path('password/',views.change_password,name='change_password')
]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'
urlpatterns = [
    path('',views.index,name='index'),
    path('search/',views.search,name='search'),
    path('graph/',views.graph,name='graph'),
    path('totalgraph/',views.totalgraph,name='totalgraph'),
    path('gisangupdate/',views.gisangupdate,name='gisangupdate'),
    path('gisangdelete/',views.gisnagdelete,name='gisangdelete'),
    path('datasend/',views.datasend,name='datasend'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko-kr">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  <!-- 차트 링크 --> 
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
  <title>창목캔디777</title>
</head>
<body>
  <!-- 부트스트랩 --> 
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> 
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script> 
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> 
  <nav class="navbar navbar-expand-sm navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{%url 'boards:index' %}">창목캔디777</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-sm-0">
          <li class="nav-item">
            <a class="nav-link" href="{%url 'boards:index' %}" tabindex="-1" aria-disabled="true">Home</a>
          </li>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            온도,습도계측
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{%url 'boards:search' %}" tabindex="-1" aria-disabled="true">Search</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{%url 'boards:graph' %}" tabindex="-1" aria-disabled="true">Graph</a></li>
            <li><a class="dropdown-item" href="{%url 'boards:totalgraph' %}" tabindex="-1" aria-disabled="true">totalgraph</a></li>
          </ul>
        </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{%url 'accounts:update' %}" tabindex="-1" aria-disabled="true">Edit</a>
            </li>
            <li class="nav-item">
              <form action="{%url 'accounts:logout' %}" method="POST">
                {% csrf_token %}
                <button class="nav-link btn btn-light">Logout</button>
              </form>
            </li>
            <li class="nav-item">
              <form action="{%url 'accounts:delete' %}" method="POST">
                {% csrf_token %}
                <button class="nav-link btn btn-light">회원탈퇴</button>
              </form>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{%url 'accounts:login' %}" tabindex="-1" aria-disabled="true">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{%url 'accounts:signup' %}" tabindex="-1" aria-disabled="true">Register</a>
            </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{%url 'boards:totalgraph' %}" tabindex="-1" aria-disabled="true">totalgraph</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container mt-3">
    {% block content %}
    {% endblock content %}
  </div>
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
</body>
</html>